### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by OliveiraDS-hub** [fansalon/TEspeX#3]
Hello!

I'm using my own fasta with consensus and I faced this error message just after the analysis get started:

creating reference file /home/oliveirads/project_aging_08-22/output_TEs/TE_transc_reference.fa
Traceback (most recent call last):
  File "TEspeX.py", line 574, in <module>
  File "TEspeX.py", line 549, in main
  File "TEspeX.py", line 274, in createReference
  File "TEspeX.py", line 258, in lineSplitting
IndexError: list index out of range

Then, I tried to change my multiline fasta to singleline (fasta_formatter -i multiline.fasta -w 0 -o singleline.fasta and now it's everything working properly!

**Comment by fansalon** [comment]
Hello and thanks for using TEspeX!

In theory, TEspeX should be working also on multiline fasta.
Would you mind to share the command used to launch TEspeX and the input fasta files (or a part of) in order to reproduce the error?

Best regards,
Federico

**Comment by OliveiraDS-hub** [comment]
You are completely right!! The problem is not associated with multi or singleline fasta! 
The problem was happening because the last line of my fasta was empty!

I solved it by using this command to eliminate any empty lines:

```sed -i '/^$/d' TE-consensus.fa```

Thanks for the answer! I hope to cite you soon!
Best regards,
Daniel

**Comment by fansalon** [comment]
Hi Daniel,

this is good news, glad you solved the issue!

Good luck with your research.

Best regards,
Federico
