### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ONAgaganb** [fansalon/TEspeX#5]
Hi,
I really like this tool! but so far I'm having some problems with it.
Here are my parameters.
```
TEspeX.py --TE /80T/cly/data/terrestris/BT3-families.fa \
--cdna /80T/cly/data/terrestris/Bombus_terrestris-GCA_910591885.2-2022_03-cdna.fa.cds.fasta \
--ncrna /80T/cly/data/terrestris/Bombus_terrestris-GCA_910591885.2-2022_03-cdna.fa.ncRNA.fasta \
--sample /80T/cly/data/terrestris/FB_rep1.txt --paired T --length 150 --out /80T/cly/data/terrestris/out --strand yes
```
Here's my error message
```
user command line arguments:
TE file = /80T/cly/data/terrestris/BT3-families.fa
cdna file = /80T/cly/data/terrestris/Bombus_terrestris-GCA_910591885.2-2022_03-cdna.fa.cds.fasta
ncrna file = /80T/cly/data/terrestris/Bombus_terrestris-GCA_910591885.2-2022_03-cdna.fa.ncRNA.fasta
sampleFile file = /80T/cly/data/terrestris/FB_rep1.txt
paired = T
readLength = 150
outDir = /80T/cly/data/terrestris/out
strand = yes
num_threads = 2 
remove = T
index = F
mask file = F
multimappers = 10

creating reference file /80T/cly/data/terrestris/out/TE_transc_reference.fa
Traceback (most recent call last):
  File "TEspeX.py", line 593, in <module>
  File "TEspeX.py", line 564, in main
  File "TEspeX.py", line 274, in createReference
  File "TEspeX.py", line 258, in lineSplitting
IndexError: list index out of range
```
I first read the issues posted by academics who have encountered problems similar to mine, so I went and checked my TE_consensus.fasta,but I didn't find anything wrong, maybe there is a problem but I don't know? I hope to get your help, thanks a lot!

**Comment by ONAgaganb** [comment]
and Here's my TE_consensus.fasta
[BT3-families.zip](https://github.com/fansalon/TEspeX/files/13201886/BT3-families.zip)

**Comment by fansalon** [comment]
Hi,

thanks for using TEspeX, and apologies for the trouble. 

My feeling from the error you sent is that the fasta files are formatted in an unexpected way. 

Are there any blank/empty lines in one of the three fasta files? 

Could you please also share ```/80T/cly/data/terrestris/Bombus_terrestris-GCA_910591885.2-2022_03-cdna.fa.cds.fasta```  and ```/80T/cly/data/terrestris/Bombus_terrestris-GCA_910591885.2-2022_03-cdna.fa.ncRNA.fasta```?

Thanks,
Federico

**Comment by ONAgaganb** [comment]
Of course, your help is sincerely appreciated!
[Bombus_terrestris-GCA_910591885.2-2022_03-cdna.fa.cds.zip](https://github.com/fansalon/TEspeX/files/13202217/Bombus_terrestris-GCA_910591885.2-2022_03-cdna.fa.cds.zip)
[Bombus_terrestris-GCA_910591885.2-2022_03-cdna.fa.ncRNA.zip](https://github.com/fansalon/TEspeX/files/13202220/Bombus_terrestris-GCA_910591885.2-2022_03-cdna.fa.ncRNA.zip)

**Comment by fansalon** [comment]
Hi,

thanks for sharing the files. As supposed, the issue here is that TEspeX cannot handle empty lines in the fasta files, and your TE consesus file has some here and there. 

I agree it is quite silly that TEspeX cannot handle such cases, so I am here sending an updated version of the ```index.py``` and ```TEspeX.py``` files.
https://www.dropbox.com/scl/fo/77w45zav6o39873k22t0r/h?rlkey=ffi8nyqjuxzrnnh94ows9i5bk&dl=0

Can you place these two files in the directory where you installed TEspeX and check if now it works?

In my hands it works, but better double check.

Thanks,
Federico

**Comment by ONAgaganb** [comment]
Hi, 
I ran it with my data and now it works, it's really an excellent tool, thanks for your help!

**Comment by fansalon** [comment]
That's great news and very glad you find TEspeX useful for your research!

All the best,
Federico
