### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by ikaufhold** [fansalon/TEspeX#7]
Hello!
Thank you for developing this great tool! I tried using it, but unfortunately I got the following error:

Traceback (most recent call last):
  File "/home/i/ikaufhol/software/TEspeX/TEspeX.py", line 593, in <module>
    main()
  File "/home/i/ikaufhol/software/TEspeX/TEspeX.py", line 565, in main
    reference = createReference(cdna, "_transc")
  File "/home/i/ikaufhol/software/TEspeX/TEspeX.py", line 273, in createReference
    for line in f:
  File "/home/i/ikaufhol/.conda/envs/TEspeX_deps/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)

The error occurs very quickly, but the output files Log.file.out and TE_transc_reference.fa still get generated. Do you maybe know what could be the cause of this problem?

Best regards,
Isabell

**Comment by fansalon** [comment]
Hello Isabell,

thanks for reaching out!

It seems like TEspeX fails in building the index. Could you please share the three fasta files (--cdna; --ncrna; --TE) you use to run TEspeX?

Thanks in advance,
Federico

**Comment by ikaufhold** [comment]
Hello Federico!

Thank you for your fast reply! Here are the files that I used.
Best regards,
Isabell

**Comment by fansalon** [comment]
Hi Isabell,

thanks for sharing the files. I think the error is related to the format of the file "GAGA-0004_CDS.fa.gz".

According to the file format, the file is a gzipped fasta file. However, when I run ```gunzip GAGA-0004_CDS.fa.gz``` I obtain a file which still appears to be compressed and not a plain fasta file.

Please, fix this, and then try to run TEspeX again.

Feel free to reopen the issue if the error persists.

Thanks,
Federico

**Comment by ikaufhold** [comment]
Hello Federico,

I fixed the file format and it's working now. Thank you very much for your help!

All the best,
Isabell
